version: '3.8'

services:
  flaskapp:
    image: flaskapp:v1
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    expose:
      - 5000

  nginx:
    image: nginx-app
    ports:
      - "80:80"
    depends_on:
      - flaskapp





